### PR TITLE
New Utility Commands

### PR DESCRIPTION
**Pull request by JuergenFuchs**
Added Coinflip Command

### CODE REVIEW

**Comment by LaCrak27** [comment]
(aka worse 8ball lmao)

**Comment by JuergenFuchs** [comment]
ok but mine is way cooler i think

**Comment by JuergenFuchs** [comment]
Now consists of the Coinflip, Weather, and Translate command

**Comment by LaCrak27** [comment]
bud i don't think this is getting merged lmao

**Comment by JuergenFuchs** [comment]
Lacrak you suck, anyways do not merge this I need to fix it first

**Comment by Astyrrean** [comment]
We don't need more bot bloat unrelated to ED or the community sorry

**Pull request closed without merging**
